services:
  backend:
    image: darwinrobles/backend-leads:latest
    pull_policy: always
    restart: always
    environment:
      PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.leads-backend.rule=Host(`utp.evolucionista.dev`)"
      - "traefik.http.routers.leads-backend.entrypoints=websecure"
      - "traefik.http.routers.leads-backend.tls=true"
      - "traefik.http.routers.leads-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.leads-backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.leads-backend.middlewares=leads-headers"
      - "traefik.http.middlewares.leads-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  dokploy-network:
    external: true
