services:
  backend:
    image: darwinrobles/backend-leads:latest
    pull_policy: always
    restart: always
    networks:
      - dokploy-network-back
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network-backend
      - traefik.http.routers.backend.rule=Host(`utp.evolucionista.dev`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8080

networks:
  dokploy-network-backend:
    external: true
